services:
  client:
    image: coe892lab42025.azurecr.io/coe892lab42025/coe892lab4:latest
    container_name: COE892_Lab4_5
    ports:
      - "3000:3000"
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - API_BASE_URL=http://localhost:8000
    restart: unless-stopped