# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import messaging_pb2 as messaging__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in messaging_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RoverServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMap = channel.unary_unary(
                '/RoverService/GetMap',
                request_serializer=messaging__pb2.Empty.SerializeToString,
                response_deserializer=messaging__pb2.MapData.FromString,
                _registered_method=True)
        self.GetCommandStream = channel.unary_stream(
                '/RoverService/GetCommandStream',
                request_serializer=messaging__pb2.Empty.SerializeToString,
                response_deserializer=messaging__pb2.Command.FromString,
                _registered_method=True)
        self.GetMineSerialNumber = channel.unary_unary(
                '/RoverService/GetMineSerialNumber',
                request_serializer=messaging__pb2.MineLocation.SerializeToString,
                response_deserializer=messaging__pb2.MineSerial.FromString,
                _registered_method=True)
        self.ReportCommandExecutionStatus = channel.unary_unary(
                '/RoverService/ReportCommandExecutionStatus',
                request_serializer=messaging__pb2.CommandStatus.SerializeToString,
                response_deserializer=messaging__pb2.Empty.FromString,
                _registered_method=True)
        self.ShareMinePIN = channel.unary_unary(
                '/RoverService/ShareMinePIN',
                request_serializer=messaging__pb2.MinePIN.SerializeToString,
                response_deserializer=messaging__pb2.Empty.FromString,
                _registered_method=True)


class RoverServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommandStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMineSerialNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportCommandExecutionStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShareMinePIN(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoverServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMap,
                    request_deserializer=messaging__pb2.Empty.FromString,
                    response_serializer=messaging__pb2.MapData.SerializeToString,
            ),
            'GetCommandStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetCommandStream,
                    request_deserializer=messaging__pb2.Empty.FromString,
                    response_serializer=messaging__pb2.Command.SerializeToString,
            ),
            'GetMineSerialNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMineSerialNumber,
                    request_deserializer=messaging__pb2.MineLocation.FromString,
                    response_serializer=messaging__pb2.MineSerial.SerializeToString,
            ),
            'ReportCommandExecutionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportCommandExecutionStatus,
                    request_deserializer=messaging__pb2.CommandStatus.FromString,
                    response_serializer=messaging__pb2.Empty.SerializeToString,
            ),
            'ShareMinePIN': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareMinePIN,
                    request_deserializer=messaging__pb2.MinePIN.FromString,
                    response_serializer=messaging__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RoverService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RoverService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RoverService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RoverService/GetMap',
            messaging__pb2.Empty.SerializeToString,
            messaging__pb2.MapData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommandStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/RoverService/GetCommandStream',
            messaging__pb2.Empty.SerializeToString,
            messaging__pb2.Command.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMineSerialNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RoverService/GetMineSerialNumber',
            messaging__pb2.MineLocation.SerializeToString,
            messaging__pb2.MineSerial.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportCommandExecutionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RoverService/ReportCommandExecutionStatus',
            messaging__pb2.CommandStatus.SerializeToString,
            messaging__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShareMinePIN(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RoverService/ShareMinePIN',
            messaging__pb2.MinePIN.SerializeToString,
            messaging__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
