name: Docker Pipeline

on:
  push:
    branches:
      - main
    paths:
      - Lab4-5/**
  workflow_dispatch:

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
    
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            registry: ${{ secrets.DOCKER_REGISTRY }}
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
    
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
    
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: ./Lab4-5
            file: ./Lab4-5/Dockerfile
            push: true
            tags: coe892lab42025.azurecr.io/coe892lab42025/coe892lab4:latest

        # - name: Remove unused Docker images
        #   run: docker image prune -af
        - name: Trigger Deploy Workflow
          uses: peter-evans/repository-dispatch@v3
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            event-type: build-completed