name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - Lab4-5/COE892Lab4-5Deployment.yaml
      - Lab4-5/COE892Lab4-5NginxConfig.yaml
  repository_dispatch:
    types: [build-completed]
  workflow_dispatch:

concurrency:
  group: deploy-environment
  cancel-in-progress: false  # Prevents new deployments from canceling an ongoing one

jobs:
  deploy:
    env:
      KUBECONFIG: /root/.kube/config
    runs-on: self-hosted
    steps:
      - name: Update Kubernetes Deployment
        run: |
            kubectl set image deployment/coe892lab4-5 coe892lab4-5=ninepiece2/coe892lab4-5:latest -n coe892
            kubectl annotate deployment coe892lab4-5 kubernetes.io/change-cause="Updated Image to ninepiece2/ninepiece2/coe892lab4-5:latest" --overwrite -n coe892
            kubectl rollout restart deployment/coe892lab4-5 -n coe892
